### PR TITLE
Desktop Version for Portfolio Website

### PR DESCRIPTION
**Pull request by faizi2500**
- [x] Desktop version looks like the one in the Figma design template.
 - [x]  Ignore two input fields for name in form.
 - [x] Use media querries.
 - [x] Use Grids and Flexbox for styling

### CODE REVIEW

**Review by Shaher-11 — APPROVED** [review]
#### Hello @faizi2500,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle::muscle:

### Optional Suggestions💡
_The following point is optional to implement however it is highly recommended!_:smile::smile:

- Increase the width of the cards below get my resume button.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

**Comment by faizi2500** [comment]
Thanks for the approval and I am looking on your optional changes. I was trying to fix that previously but when I increase their width, they just happen to take up extra space horizontally giving my UI a bad touch. Is there any suggestion how I can fix this? 
P.s. I am trying it myself and once again thanks for the feedback :)

**Comment by Shaher-11** [comment]
Specify the width of each individual card we just need to reduce the space between them a little bit that's all.
Btw You have done a great job.
Keep up the good work:clap::clap:

**Comment by faizi2500** [comment]
Thanks for the appreciation, means a lot :)

**Pull request merged**
